version: '3.1'

services:

  db:
    container_name: pg1
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin1234

  adminer:
    container_name: adminer1
    image: adminer
    restart: always
    ports:
      - 8085:8080