version: '3.7'
services:
  postgres1:
    image: postgres
    container_name: pg2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=postgres
    ports:
      - '5444:5432'
    volumes:
      - c:/db/postgresql/data:/var/lib/postgresql/data
      - c:/db/postgresql/backups:/var/backups